"""
Test script for checking the streaming API endpoint.
"""
import requests
import json
import sys

# API endpoint for streaming chat
CONVERSATION_ID = 1  # Generated by prepare_test.py
API_URL = "http://localhost:8000/api/v1/chat/{}/stream".format(CONVERSATION_ID)
MESSAGE = "Merhaba, streaming testi yapıyorum. Geniş bir cevap verir misin?"

def test_streaming():
    """Test the streaming endpoint by sending a message and processing the response."""
    print(f"Sending request to {API_URL}")
    print(f"Message: {MESSAGE}")
    
    # Send the request
    try:
        response = requests.post(
            API_URL,
            json={"message": MESSAGE},
            stream=True,
            headers={"Content-Type": "application/json"}
        )
        
        # Check if the request was successful
        if response.status_code != 200:
            print(f"Error: Status code {response.status_code}")
            print(response.text)
            return
        
        # Process the streaming response
        print("\nReceiving streaming response:")
        print("-" * 50)
        
        for line in response.iter_lines():
            if line:
                # Server-sent events format: "data: [content]"
                line = line.decode('utf-8')
                if line.startswith('data:'):
                    content = line[5:].strip()
                    if content == "[DONE]":
                        print("\nStreaming complete.")
                        break
                    print(content, end='', flush=True)
        
        print("\n" + "-" * 50)
        
    except requests.exceptions.RequestException as e:
        print(f"Request failed: {e}")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    test_streaming()
